multithread http proxy
kestfor/os pull request #7
Opened 2024-10-23 03:12 UTC by kestfor

2024-11-22 07:17 UTC, Silhouette22 requested changes

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/channel/channel.c
> +    free(ch);
А rwlock уничтожить?

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/channel/channel.c
> +void empty_channel(channel *ch) {
Я бы лучше сделал не просто empty, а set_empty. Текущее название можно слишком по-разному интерпретировать. Допустим, проверка на то, пустой ли канал. Или создание нового пустого канала, к примеру

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/channel/channel.c
> +void empty_channel(channel *ch) {
Вообще, неплохой идеей будет немного изменить подход к именованию функций. Можно сначала писать сущность, к которой относится функция, а затем действие, которое она делает.

Возьмем пример - функции библиотеки pthread.

Они все начинаются с префикса pthread_*, затем идет название того, на что обращено действие, например mutex, а затем уже само действие, например init

Таким образом получается группировка функций по названию. И когда ты в среде разработки вводишь pthread_mutex_ тебе автодополнение подсказывает все доступные методы для данного типа. Удобно? Мне кажется, да.

В твоем случае тогда получится что-то типа такого:

channel_create()
channel_delete()
channel_set_whole()
channel_is_whole()
channel_add()
channel_write()
channel_read()
channel_set_empty()

Как будто, это поможет тебе же самому не запутаться в методах, если вдруг их будет очень много.



Если что, считай это не как замечание, а как совет, можешь сам решить, хочешь так делать или нет

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/channel/channel.c
> +    return ch->actual_len;
К слову, а тут не нужна блокировка?

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/client.c
> +    inet_pton(AF_INET, "127.0.0.1", &server_addr.sin_addr);
Наверное, лучше иметь возможность задать адрес через аргументы, чтобы потестить не только на локалхосте

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/client.c
> +    inet_pton(AF_INET, "127.0.0.1", &server_addr.sin_addr);
Хотя ладно, пофиг, можно и любой другой клиент, например wget, использовать)

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/hashmap/hashmap.c
> +            } else if (temp->data.cached_time <= oldest_time) {
А, разве, это условие когда-либо будет false? У тебя в кэше может появиться будущее время?

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/hashmap/hashmap.c
> +            } else if (temp->data.cached_time <= oldest_time) {
А, понял, ты тут искал самую старую запись в кэше. Но я не вижу, где бы ты обновлял `oldest_time`, так что она у тебя всегда на текущее время ссылается

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/hashmap/hashmap.c
> +            } else if (temp->data.cached_time <= oldest_time) {
Наверное, чуть ниже должно быть еще `oldest_time = temp.data.cached_time`

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/hashmap/hashmap.c
> +            pthread_rwlock_unlock(&hashmap->rwlock);
Если ты вот тут "разрываешь" свою критическую секцию, то считай, что все проверки, которые ты до этого делал, больше не действительны. Ты не можешь полагаться на то, что ты проверил в рамках критической секции, когда вышел из неё и зашел в другую секцию.

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/request.h
> +    get = 0,
Небольшой совет по использованию enum'ов. Лучше начинать с 1-цы, а не с нуля.
Что будет, если ты просто объявишь переменную типа своего enum'а, но не будешь инициализировать?

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/server.c
> +void *cleanup(void *args) {
А не слишком ли нагрузит систему такой агрессивный cleanup?

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/server.c
> +            usleep(10000);
Засыпать - это не хорошо. Лучше дождаться именно того момента, пока не появятся данные, другим способом

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/server.c
> +    printf("cache miss, connecting to host...\n");
Т.е., у тебя происходит перезапрос с сервера, если запись в кэше "протухла"? Неплохая идея

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/server.c
> +    pthread_create(&tid, NULL, read_data, &args);
Еще бы, конечно, проверить на ошибки, а то вдруг и не создался никакой тред-то..

2024-11-22 07:17 UTC, Silhouette22 commented on autumn/project/server.c
> +    number_read = read(client_socket, buff, BUFF_SIZE);
А если за 1 read весь запрос от клиента не считался?

2024-12-09 14:06 UTC, Silhouette22 commented on autumn/project/channel/channel.c
>      pthread_cond_wait(&ch->cond_var, &ch->cond_mutex);
Вопрос - какого условия ты дожидаешься данной условной переменной? Условная переменная всегда связана с каким-то условием. 
А использование одновременно rwlock и mutex вызывает у меня некоторые вопросы. Скорее всего, какой-то из двух примитивов лишний тут

2024-12-09 14:06 UTC, Silhouette22 commented on autumn/project/channel/channel.c
> +    pthread_mutex_lock(&ch->cond_mutex);
Мне кажется, что раз ты перешел на мьютексы с условными переменными, то и стоит уж их использовать полностью.
Комбинация методов `mutex_lock`, `cond_broadcast `и `mutex_unlock ` выглядит так, как будто тебе нужно было как-то вызвать отправить сигнал по условной переменной, но ты не придумал ничего лучше. 
К слову, для отправки сигнала по условной переменной не обязательно захватывать связанный мьютекс.


Предлагаю тебе выбрать что-то одно, либо использовать мьютексы и условные переменные для задания критической секции и сигнализирования о событии, либо задать блокировки чтения/записи для задания критической секции, а для сообщения о событии использовать, например, сигналы и `sigwait`

2024-12-09 14:06 UTC, Silhouette22 commented on autumn/project/hashmap/hashmap.c
> +bool insert_and_capture(HashMap *hashMap, const char *key, const char *value, cached_data *out) {
А это где-либо используется?

2024-12-09 15:38 UTC, kestfor commented on autumn/project/hashmap/hashmap.c
> +bool insert_and_capture(HashMap *hashMap, const char *key, const char *value, cached_data *out) {
тестил, в итоге нет

2024-12-09 15:52 UTC, Silhouette22 commented on autumn/project/channel/channel.c
>      pthread_cond_wait(&ch->cond_var, &ch->cond_mutex);
Опять же, вопрос остается открытым, за какое условие отвечает эта условная переменная?

2024-12-09 15:52 UTC, Silhouette22 commented on autumn/project/server.c
> +    volatile int offset = 0;
От `volatile` тут особо эффекта не будет, ибо это локальная в рамках функции переменная

2024-12-09 15:54 UTC, kestfor commented on autumn/project/server.c
> +    volatile int offset = 0;
я сейчас тестил, без этого valotile у меня собирается программа неработающая, он как-то оптимизирует offset так, что он равен 0 на каждой новой итерации цикла, хотя раньше без этого все работало

2024-12-09 15:57 UTC, kestfor commented on autumn/project/server.c
> +    volatile int offset = 0;
переменная для ожидания новой партии данных, в целом можно сделать цикл и ждать, если вдруг на этом канале другой поток ожидает, но я решил просыпаться при каждом сообщении о том что появились данные в канале и уже проверять кому оно приходит во внешнем цикле

2024-12-13 09:40 UTC, Silhouette22 approved these changes

2024-12-14 09:25 UTC, merged